### ISSUE TITLE
7주차 - Oracle ROWNUM

### ISSUE THREAD

**Issue by heewonham** [SogangSpring/JPAStudy#32]
* ROWNUM은 쿼리 내에서 사용 가능한 (실제 컬럼이 아닌) 가상 컬럼(pseudocolumn)입니다.
* ROWNUM에는 숫자 1, 2, 3, 4, ... N의 값이 할당됩니다. 여기서 N 은 ROWNUM과 함께 사용하는 로우의 수를 의미합니다. ROWNUM의 값은 로우에 영구적으로 할당되지 않습니다(이는 사람들이 많이 오해하는 부분이기도 합니다).
* 테이블의 로우는 숫자와 연계되어 참조될 수 없습니다. 따라서 테이블에서 "row 5"를 요청할 수 있는 방법은 없습니다. "row 5"라는 것은 존재하지 않기 때문입니다.
* ROWNUM 값은 **쿼리의 조건절이 처리되고 난 이후, 그리고 sort, aggregation이 수행되기 이전에 할당**됩니다.
.
.
.
* 예를 들어, 
  * select * from A where rownum > 10 and rownum <= 20
    * 결과는 나오지 않음
    * ROWNUM의 값은 쿼리 조건절 처리된 이후 나오기 때문
  * select * from (select * from A) where rownum > 10 and rownum <= 20
    * 으로 수정해야한다.
  * select * from (select * from A order by date desc) where rownum > 10 and rownum <= 20
    * 이것 역시 원하는 결과는 나오지 않는다.
    * 왜냐하면 sort 이전에 수행되기 이전에 ROWNUM이 할당되기 때문이다
  * select * from (select * from (selct * from A order by date desc)  aa ) where rownum > 10 and rownum <= 20
    * 으로 수정해야한다.

출처 1 : https://agreeable.tistory.com/entry/ORACLE-ROWNUM-%ED%99%9C%EC%9A%A9

출처 2 : https://5dol.tistory.com/127 [5dol Story]

**Comment by TaeBeomShin** [comment]
추가 이슈 : ROW NUM 사용 시 성능을 개선할 수 있는 이유?

**Comment by kshired** [comment]
https://kdarkdev.tistory.com/272

여기를 보면 정확한 이유는 없는데 확실히 쿼리 속도가 빨라지는 것은 보이네요.. 왜일까요ㅜ

**Comment by kshired** [comment]
```sql
SELECT
  *
FROM
  (SELECT * FROM EMP ORDER BY ENAME)
WHERE
  ROWNUM <= 5;
```
**oracle에서 ORDER BY 절을 사용하여 ROWNUM으로 자르면** 
ex) `SELECT * FROM (SELECT * FROM EMP ORDER BY ENAME) WHERE ROWNUM <= 5;`

1. 테이블을 스캔합니다.
2. **ROWNUM의 n개 만큼 정렬을 수행하고 n개만큼 가져옵니다.** (이는 그 뒤 정렬은 생각하지 않습니다.)

ROWNUM을 사용하지 않고 쿼리문을 실행하여 자를 시엔

1. 테이블을 스캔합니다.
2. **전체적인 정렬**을 수행합니다.
3. n개만큼 자르거나 사용합니다.


----

제가 생각하기엔 위와 같은 특성때문에 특정 개수만 가져오고 그 뒤에 sort해서 더 빠른게 아닐까 싶네요

@TaeBeomShin @heewonham  참고바랍니다.

[**JPA 이슈**](https://github.com/SogangSpring/JPAStudy/issues/34)에다가 잘못 적어놨던걸 ( 어디갔나 했네요.. )

지금 봤네요 .. ㅋㅋㅋㅋ 일단 여기서 close 할게요!
