### ISSUE TITLE
JPA 사용자 정의함수 추가 내용

### ISSUE THREAD

**Issue by kshired** [SogangSpring/JPAStudy#34]
[링크](https://thorben-janssen.com/database-functions/)

참고 부탁드립니다.

**Comment by TaeBeomShin** [comment]
- 사용자 정의 함수는 데이터베이스에 정의하고,

**Comment by kshired** [comment]
```sql
SELECT
  *
FROM
  (SELECT * FROM EMP ORDER BY ENAME)
WHERE
  ROWNUM <= 5;
```
**oracle에서 ORDER BY 절을 사용하여 ROWNUM으로 자르면** 
ex) `SELECT * FROM (SELECT * FROM EMP ORDER BY ENAME) WHERE ROWNUM <= 5;`

1. 테이블을 스캔합니다.
2. **ROWNUM의 n개 만큼 정렬을 수행하고 n개만큼 가져옵니다.** (이는 그 뒤 정렬은 생각하지 않습니다.)

ROWNUM을 사용하지 않고 쿼리문을 실행하여 자를 시엔

1. 테이블을 스캔합니다.
2. **전체적인 정렬**을 수행합니다.
3. n개만큼 자르거나 사용합니다.


----

제가 생각하기엔 위와 같은 특성때문에 특정 개수만 가져오고 그 뒤에 sort해서 더 빠른게 아닐까 싶네요

@TaeBeomShin @heewonham  참고바랍니다.
