### ISSUE TITLE
1주차 - 의문점 및 생소한 개념

### ISSUE THREAD

**Issue by TaeBeomShin** [SogangSpring/JPAStudy#5]
# 1주차 의문점 및 개념
---
### 데이터베이스의 패러다임은 뭘까?
- 일반적으로, DB 패러다임이란 DB 를 저장하고 관리하는 방법을 의미함..!
- 책에서 말하는 패러다임 불일치에서의 db 패러다임은 데이터 중심의 구조화와 집합적인 사고를 뜻하는 걸로 추정.

### 객체의 참조라는건 주소를 말하는 것?
[참조와 주소의 차이](https://namocom.tistory.com/869)
-  object referenece(객체 참조)는 클래스로 만든 객체의 주소 또는 참조값
- 자바에서는 C언어와 다르게 메모리 상의 주소가 참조의 대상이 아니다. 자바에서는 객체의 주소 대신 참조값이라는 것을 할당받는다.
- 자바에서는 주소와 참조값이 다른의미..

### SQL힌트란?
[sql 힌트의 개념](https://velog.io/@gillog/SQL-Plan-Hint)
- SQL사용자가 SQL 구문에 작성하는 것을 뜻한다. 오라클이 항상 최적의 실행 경로를 만들어 내기는 불가능하기 때문에 직접 최적의 실행 경로를 작성해 주는 것이다

### 벤더 독립성
- 벤더와 벤더의 독립성은 데이터베이스를 만든 회사에 대한 내용
- 흔히 산업용어로 벤더는 생산회사를 의미함!
- 각 데이터베이스에 독립적이다 라는 말을 벤더 독립성을 표현함.

### 스레드 세이프
- 멀티 스레드 프로그래밍에서 일반적으로 어떤 함수나 변수, 혹은 객체가 여러 스레드로부터 동시에 접근이 이루어져도 프로그램의 실행에 문제가 없음
- Not thread safe는 반대.

### @Entity와 같은 어노테이션은 어떻게 동작하는가
- [정리된글 링크](https://donghyeon.dev/spring/2020/08/18/Spring-Annotation%EC%9D%98-%EC%9B%90%EB%A6%AC%EC%99%80-Custom-Annotation-%EB%A7%8C%EB%93%A4%EC%96%B4%EB%B3%B4%EA%B8%B0/)
- [공식문서 번역 & 소개](https://github.com/SogangSpring/JPAStudy/issues/5#issue-998397666)

**Comment by kshired** [comment]
1주차 해결!
SQL 힌트는 각자 보는걸로..

**Comment by kshired** [comment]
1주차 해결!
SQL 힌트는 각자 보는걸로..
